services:
  order-service:
    build: ./order-service
    ports:
      - "5001:5000"
    environment:
      - USER_SERVICE_URL=http://user-service:5000
      - NOTIFICATION_SERVICE_URL=http://notification-service:5000
    depends_on:
      - user-service
      - notification-service
    networks:
      - lab-network

  user-service:
    build: ./user-service
    ports:
      - "5002:5000"
    networks:
      - lab-network

  notification-service:
    build: ./notification-service
    ports:
      - "5003:5000"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge